import { v2 as cloudinary } from 'cloudinary';

const { CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_SECRET } = process.env;
if (!CLOUDINARY_CLOUD_NAME || !CLOUDINARY_API_KEY || !CLOUDINARY_SECRET)
    throw new Error('missing one or more Cloudinary env variables');

cloudinary.config({ 
    secure: true,
    hide_sensitive: true,
    cloud_name: CLOUDINARY_CLOUD_NAME, 
    api_key: CLOUDINARY_API_KEY, 
    api_secret: CLOUDINARY_SECRET 
});

/**
 * Because we are using normal URL's for images, we can just simply use the img src atribute to download them,
 * meaning we shouldnt ever need a "get image" function, this should be handled by the client side.
 */


/**
 * Uploads an image to Cloudinary from a buffer. The filename is optional, if not provided it will be generated by Cloudinary.
 * @param {Buffer} buffer 
 * @param {string} filename 
 * @returns {Promise<{id: string, url: string}>} 
 */
export async function uploadImageFromBuffer(buffer, filename=null) {

    const uploadResult = await new Promise((resolve, reject) => {
        cloudinary.uploader.upload_stream(
            {
                public_id: filename.replace(/\.[^/.]+$/, '') || undefined,
                resource_type: 'auto',
            },
            (error, result) => {
                if (error) {
                    console.error('Upload error:', error);
                    reject(error);
                } else {
                    console.log('Upload result:', result);
                    resolve(result);
                }
            }
        ).end(buffer);
    });

// ? We might want to just return the promise result, but this lets us only reveal certain things from the upload 
    return {
        id: uploadResult.public_id,
        url: uploadResult.secure_url || uploadResult.url,
    };
}


/**
 * Uploads an image to Cloudinary from a URL. The filename is optional, if not provided it will be generated by Cloudinary.
 * @param {string} imageURL 
 * @param {string} filename 
 * @returns 
 */
export async function uploadImageFromURL(imageURL, filename=null) {
    const uploadResult = await cloudinary.uploader.upload(
        imageURL,
        {
            public_id: filename ? filename : extractFilename(imageURL),
            resource_type: 'auto',
        }
    );

    // ? We might want to just return the promise result, but this lets us only reveal certain things from the upload 
    
    return {
        id: uploadResult.public_id,
        url: uploadResult.secure_url || uploadResult.url,
    };
}



/**
 * This method attempts to automatically determine the type of the image source and upload it accordingly. It supports Buffer, URL string, and local file path string. The filename is optional, if not provided it will be generated by Cloudinary.
 * @param {Buffer | string} imageSource 
 * @param {string} filename 
 * @returns 
 */
export async function autoUploadImage(imageSource, filename=null) {
    if (imageSource instanceof Buffer) {
        return await uploadImageFromBuffer(imageSource, filename);
    } else if (typeof imageSource === 'string') {
        return await uploadImageFromURL(imageSource, filename);
    } else {
        throw new Error('Unsupported image source type');
    }
}


/**
 * Deletes an image from Cloudinary given its URL. It extracts the public_id from the URL and uses it to delete the image. Note that this will permanently delete the image from Cloudinary, so use with caution.
 * @param {string} imageURL 
 * @returns {Promise}
 */
export async function deleteImage(imageURL) {
    // Extract public_id from the URL
    const urlParts = imageURL.split('/');
    const publicId = urlParts[urlParts.length - 1].split('.')[0];
    return new Promise((resolve, reject) => {
        cloudinary.uploader.destroy(publicId, { resource_type: 'image' }, (error, result) => {
            if (error) {
                console.error('Delete error:', error);
                reject(error);
            } else {
                console.log('Delete result:', result);
                resolve(result);
            }
        });
    });
}

/**
 * Extracts the filename from a given image path, either local or web.
 * @param {string} imagePath 
 * @returns {string} the image's public id based on the cloundiary image
 */
function extractFilename(imagePath) {
    return imagePath.split('/').pop().replace(/\.[^/.]+$/, "");
}



export default { 
    uploadImageFromBuffer,
    uploadImageFromURL,
    autoUploadImage,
    deleteImage,
};
