# Use a Node image that matches your local development environment
image: node:20

# Define variables globally (these will be pulled from your GitLab CI/CD settings)
variables:
  token: $token

stages:
  - deploy

# Deployment for all branches except 'main' (Preview)
deploy_preview:
  stage: deploy
  rules:
    # - if: '$CI_COMMIT_BRANCH == "Development"'
  script:
    - npm install --global vercel
    - npm install
    - npx vercel --token=$token

# Prints all CI/CD environment variables (keys and values)
print_ci_cd_variables:
  stage: deploy
  script:
    - echo "Printing all environment variables available in this job:"
    - printenv | sort

# Deployment for the 'main' branch (Production)
deploy_production:
  stage: deploy
  rules:
    # - if: '$CI_COMMIT_BRANCH == "Development"'
  script:
    - npm install --global vercel
    - npm install
    - npx vercel --token=$token --prod
